/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_megacreep_jinotify_NativeInotify */

#ifndef _Included_com_megacreep_jinotify_NativeInotify
#define _Included_com_megacreep_jinotify_NativeInotify
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_megacreep_jinotify_NativeInotify
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_megacreep_jinotify_NativeInotify_init
  (JNIEnv *, jobject);

/*
 * Class:     com_megacreep_jinotify_NativeInotify
 * Method:    init1
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_megacreep_jinotify_NativeInotify_init1
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_megacreep_jinotify_NativeInotify
 * Method:    addWatch
 * Signature: (ILjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_megacreep_jinotify_NativeInotify_addWatch
  (JNIEnv *, jobject, jint, jstring, jint);

/*
 * Class:     com_megacreep_jinotify_NativeInotify
 * Method:    removeWatch
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_megacreep_jinotify_NativeInotify_removeWatch
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_megacreep_jinotify_NativeInotify
 * Method:    takeEvent
 * Signature: (II)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_megacreep_jinotify_NativeInotify_takeEvent
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
